# Numpy

### Numpy

### **1. Basics: Creating and Inspecting Arrays**

``` python
import numpy as np

*# 1D array (vector)*
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Shape:", array_1d.shape)
print("Dimension:", array_1d.ndim)
print("Size:", array_1d.size)

*# 2D array (matrix)*
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)
print("Shape:", array_2d.shape)  *# (rows, columns)*
print("Dimension:", array_2d.ndim)
print("Size:", array_2d.size)

*# Array with zeros*
zeros = np.zeros((3, 4))  *# 3 rows, 4 columns*
print("\nZeros Array:\n", zeros)

*# Array with ones*
ones = np.ones((2, 3))
print("\nOnes Array:\n", ones)

*# Range of numbers*
range_array = np.arange(0, 10, 2)  *# Start, stop, step*
print("\nRange Array:", range_array)
```

### **2. Array Manipulation: Reshaping, Indexing, and Slicing**

``` python
import numpy as np

*# Sample 1D array*
data = np.arange(12)  *# 0 to 11*
print("Original 1D:", data)

*# Reshape to 2D*
data_2d = data.reshape(3, 4)  *# 3 rows, 4 columns*
print("\nReshaped to 2D:\n", data_2d)

*# Indexing*
print("\nElement at (1, 2):", data_2d[1, 2])  *# Row 1, Column 2*
print("First row:", data_2d[0, :])
print("Second column:", data_2d[:, 1])

*# Slicing*
slice_2d = data_2d[1:, 2:]  *# Rows 1 onwards, Columns 2 onwards*
print("\nSliced array:\n", slice_2d)

*# Stacking arrays*
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked = np.vstack((array1, array2))  *# Vertical stack*
print("\nVertically stacked:\n", stacked)
```

### **3. Mathematical Operations**

``` python
import numpy as np

*# Sample arrays*
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

*# Element-wise operations*
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)

*# Matrix operations*
matrix = np.array([[1, 2], [3, 4]])
print("\nMatrix:\n", matrix)
print("Matrix multiplied by 2:\n", matrix * 2)
print("Matrix sum:", np.sum(matrix))

*# Statistical operations*
data = np.array([1, 2, 3, 4, 5])
print("\nMean:", np.mean(data))
print("Standard Deviation:", np.std(data))
print("Max:", np.max(data))
```

### Review based Numpy

-   **Creation & Initialization**

    \## **✅ 1. Creating Arrays from Lists & Tuples**

    ``` python
    python
    CopyEdit
    import numpy as np

    # From a List
    arr1 = np.array([1, 2, 3, 4, 5])

    # From a Tuple
    arr2 = np.array((10, 20, 30))

    print(arr1)   # Output: [1 2 3 4 5]
    print(arr2)   # Output: [10 20 30]
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Creating Arrays with Default Values**

    ``` python
    python
    CopyEdit
    arr_zeros = np.zeros((3, 3))   # 3x3 matrix of zeros
    arr_ones = np.ones((2, 2))     # 2x2 matrix of ones
    arr_full = np.full((2, 3), 7)  # 2x3 matrix filled with 7
    arr_identity = np.eye(4)       # 4x4 Identity matrix

    print(arr_zeros)
    print(arr_ones)
    print(arr_full)
    print(arr_identity)
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Creating Arrays with a Range of Values**

    ``` python
    python
    CopyEdit
    arr_range = np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]
    arr_linspace = np.linspace(1, 10, 5)  # [1, 3.25, 5.5, 7.75, 10]

    print(arr_range)
    print(arr_linspace)
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Creating Random Arrays**

    ``` python
    python
    CopyEdit
    arr_rand = np.random.rand(3, 3)   # 3x3 matrix of random values (0-1)
    arr_randint = np.random.randint(1, 100, (2, 2))  # 2x2 matrix of random integers
    arr_randn = np.random.randn(4)  # 4 values from normal distribution

    print(arr_rand)
    print(arr_randint)
    print(arr_randn)
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. Creating Special Arrays**

    ``` python
    python
    CopyEdit
    arr_empty = np.empty((2, 2))  # Uninitialized values
    arr_identity = np.identity(3)  # 3x3 Identity matrix

    print(arr_empty)
    print(arr_identity)
    ```

    ------------------------------------------------------------------------

    \## **🔥 TL;DR: Summary Table**

    | Method    | Example                 | Output                                 |
    |------------------------|------------------------|------------------------|
    | From List | `np.array([1, 2, 3])`   | `[1 2 3]`                              |
    | Zeros     | `np.zeros((2,2))`       | `[[0. 0.], [0. 0.]]`                   |
    | Ones      | `np.ones((2,2))`        | `[[1. 1.], [1. 1.]]`                   |
    | Full      | `np.full((2,2), 7)`     | `[[7 7], [7 7]]`                       |
    | Arange    | `np.arange(1, 10, 2)`   | `[1 3 5 7 9]`                          |
    | Linspace  | `np.linspace(1, 10, 5)` | `[1. 3.25 5.5 7.75 10.]`               |
    | Random    | `np.random.rand(3,3)`   | `[[0.24 0.56 0.78], [0.12 0.92 0.33]]` |
    | Identity  | `np.eye(3)`             | `[[1 0 0], [0 1 0], [0 0 1]]`          |

-   **Indexing & Slicing**

    \## **✅ 1. Indexing (Accessing Elements)**

    NumPy supports **both 1D and multi-dimensional indexing**.

    ``` python
    python
    CopyEdit
    import numpy as np

    arr = np.array([10, 20, 30, 40, 50])

    # Access elements using index (0-based)
    print(arr[0])  # Output: 10
    print(arr[2])  # Output: 30
    print(arr[-1]) # Output: 50 (Negative index starts from the end)
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Slicing (Extracting Subarrays)**

    **Syntax:** `array[start:stop:step]`

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

    # Basic Slicing
    print(arr[1:5])    # Output: [20 30 40 50] (From index 1 to 4)

    # Slicing with Step
    print(arr[::2])    # Output: [10 30 50 70] (Every 2nd element)

    # Reverse Array
    print(arr[::-1])   # Output: [80 70 60 50 40 30 20 10]
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Indexing in Multi-Dimensional Arrays**

    For **2D & 3D arrays**, use **row, column** format:

    ``` python
    python
    CopyEdit
    arr2D = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

    # Access a single element
    print(arr2D[1, 2])  # Output: 6  (Row 1, Column 2)

    # Get entire row
    print(arr2D[1, :])  # Output: [4 5 6] (Row 1)

    # Get entire column
    print(arr2D[:, 2])  # Output: [3 6 9] (Column 2)

    # Sub-matrix
    print(arr2D[0:2, 1:3])
    # Output:
    # [[2 3]
    #  [5 6]]
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Boolean Indexing (Conditional Filtering)**

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50])

    # Find values greater than 25
    print(arr[arr > 25])  # Output: [30 40 50]

    # Find even numbers
    print(arr[arr % 2 == 0])  # Output: [10 20 30 40 50]
    ```

    ------------------------------------------------------------------------

-   **Reshaping & Manipulation**

    \## **✅ 1. Reshaping Arrays (`.reshape()`)**

    ``` python
    python
    CopyEdit
    import numpy as np

    arr = np.array([1, 2, 3, 4, 5, 6])

    # Reshape into 2x3 matrix
    arr_reshaped = arr.reshape(2, 3)

    print(arr_reshaped)
    # Output:
    # [[1 2 3]
    #  [4 5 6]]
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Flattening an Array (`.ravel()` & `.flatten()`)**

    ``` python
    python
    CopyEdit
    arr2D = np.array([[1, 2, 3],
                      [4, 5, 6]])

    # Flatten using ravel (returns a view)
    print(arr2D.ravel())  # Output: [1 2 3 4 5 6]

    # Flatten using flatten (returns a copy)
    print(arr2D.flatten())  # Output: [1 2 3 4 5 6]
    ```

    📌 **Difference:**

    ✔ `ravel()` gives a **view** (modifications affect the original).

    ✔ `flatten()` returns a **new copy**.

    ------------------------------------------------------------------------

    \## **✅ 3. Changing Array Shape (`.resize()`)**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5, 6])
    arr.resize(3, 2)

    print(arr)
    # Output:
    # [[1 2]
    #  [3 4]
    #  [5 6]]
    ```

    📌 **Use `.resize()` if you want to modify the original array!**

    ------------------------------------------------------------------------

    \## **✅ 4. Stacking & Concatenation**

    \### **🔹 Horizontal Stacking (`hstack()`)**

    ``` python
    python
    CopyEdit
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])

    print(np.hstack((arr1, arr2)))
    # Output: [1 2 3 4 5 6]
    ```

    \### **🔹 Vertical Stacking (`vstack()`)**

    ``` python
    python
    CopyEdit
    print(np.vstack((arr1, arr2)))
    # Output:
    # [[1 2 3]
    #  [4 5 6]]
    ```

    \### **🔹 Concatenation (`concatenate()`)**

    ``` python
    python
    CopyEdit
    print(np.concatenate((arr1, arr2)))
    # Output: [1 2 3 4 5 6]
    ```

    📌 **Difference?** `hstack()` joins **horizontally**, `vstack()`
    joins **vertically**, `concatenate()` is **flexible**.

    ------------------------------------------------------------------------

    \## **✅ 5. Splitting Arrays (`split()`)**

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50, 60])

    # Split into 3 parts
    print(np.split(arr, 3))
    # Output: [array([10, 20]), array([30, 40]), array([50, 60])]
    ```

    ------------------------------------------------------------------------

-   **Mathematical Operations**

    \## **✅ 1. Element-wise Operations**

    ``` python
    python
    CopyEdit
    import numpy as np

    arr1 = np.array([1, 2, 3, 4])
    arr2 = np.array([5, 6, 7, 8])

    print(arr1 + arr2)  # Output: [ 6  8 10 12]
    print(arr1 - arr2)  # Output: [-4 -4 -4 -4]
    print(arr1 * arr2)  # Output: [ 5 12 21 32]
    print(arr1 / arr2)  # Output: [0.2 0.3333 0.4286 0.5]
    print(arr1 ** 2)    # Output: [ 1  4  9 16] (Exponentiation)
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Aggregate Functions**

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50])

    print(np.sum(arr))    # Output: 150
    print(np.mean(arr))   # Output: 30.0
    print(np.max(arr))    # Output: 50
    print(np.min(arr))    # Output: 10
    print(np.std(arr))    # Output: 14.14 (Standard Deviation)
    print(np.var(arr))    # Output: 200.0 (Variance)
    print(np.median(arr)) # Output: 30.0
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Trigonometric Functions**

    ``` python
    python
    CopyEdit
    angles = np.array([0, 30, 45, 60, 90])

    # Convert degrees to radians
    radians = np.deg2rad(angles)

    print(np.sin(radians))  # Output: [0.  0.5  0.707  0.866  1.]
    print(np.cos(radians))  # Output: [1.  0.866  0.707  0.5  0.]
    print(np.tan(radians))  # Output: [0.  0.577  1.  1.732  inf]
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Logarithmic & Exponential Functions**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 10, 100])

    print(np.log(arr))   # Output: [0.  2.302  4.605]  (Natural log)
    print(np.log10(arr)) # Output: [0.  1.  2.]       (Base 10 log)
    print(np.exp(arr))   # Output: [2.718 22026.46 2.688e+43] (Exponential)
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. Rounding & Floor/Ceil**

    ``` python
    python
    CopyEdit
    arr = np.array([3.14, 2.71, 1.41, 0.99])

    print(np.round(arr, 1))  # Output: [3.1 2.7 1.4 1. ]
    print(np.floor(arr))      # Output: [3. 2. 1. 0.]
    print(np.ceil(arr))       # Output: [4. 3. 2. 1.]
    ```

    ------------------------------------------------------------------------

    \## **✅ 6. Modulo & Absolute Value**

    ``` python
    python
    CopyEdit
    arr = np.array([-10, -5, 0, 5, 10])

    print(np.abs(arr))      # Output: [10  5  0  5 10]
    print(np.mod(arr, 3))   # Output: [2 1 0 2 1] (Remainder after division)
    ```

    ------------------------------------------------------------------------

-   **Linear Algebra**

    \## **✅ 1. Matrix Multiplication**

    ``` python
    python
    CopyEdit
    import numpy as np

    A = np.array([[1, 2],
                  [3, 4]])

    B = np.array([[5, 6],
                  [7, 8]])

    # Matrix multiplication (dot product)
    print(np.dot(A, B))
    # Output:
    # [[19 22]
    #  [43 50]]

    # Alternative using @ operator
    print(A @ B)
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Identity Matrix (`np.eye()`)**

    ``` python
    python
    CopyEdit
    I = np.eye(3)  # 3x3 identity matrix
    print(I)
    # Output:
    # [[1. 0. 0.]
    #  [0. 1. 0.]
    #  [0. 0. 1.]]
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Transpose of a Matrix (`.T`)**

    ``` python
    python
    CopyEdit
    A = np.array([[1, 2, 3],
                  [4, 5, 6]])

    print(A.T)
    # Output:
    # [[1 4]
    #  [2 5]
    #  [3 6]]
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Determinant of a Matrix (`np.linalg.det()`)**

    ``` python
    python
    CopyEdit
    A = np.array([[1, 2],
                  [3, 4]])

    print(np.linalg.det(A))
    # Output: -2.0
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. Inverse of a Matrix (`np.linalg.inv()`)**

    ``` python
    python
    CopyEdit
    A = np.array([[4, 7],
                  [2, 6]])

    A_inv = np.linalg.inv(A)
    print(A_inv)
    # Output:
    # [[ 0.6 -0.7]
    #  [-0.2  0.4]]
    ```

    ------------------------------------------------------------------------

    \## **✅ 6. Solving Linear Equations (`Ax = b`)**

    ``` python
    python
    CopyEdit
    A = np.array([[3, 1],
                  [1, 2]])

    b = np.array([9, 8])

    x = np.linalg.solve(A, b)
    print(x)
    # Output: [2. 3.]  (Solution for x₁ = 2, x₂ = 3)
    ```

    ------------------------------------------------------------------------

    \## **✅ 7. Eigenvalues & Eigenvectors**

    ``` python
    python
    CopyEdit
    A = np.array([[4, -2],
                  [1, 1]])

    eig_values, eig_vectors = np.linalg.eig(A)

    print("Eigenvalues:", eig_values)
    print("Eigenvectors:\n", eig_vectors)
    ```

    ------------------------------------------------------------------------

-   **Statistical Functions**

    \## **✅ 1. Basic Statistics**

    ``` python
    python
    CopyEdit
    import numpy as np

    arr = np.array([10, 20, 30, 40, 50])

    print("Mean:", np.mean(arr))       # Output: 30.0
    print("Median:", np.median(arr))   # Output: 30.0
    print("Standard Deviation:", np.std(arr))  # Output: 14.14
    print("Variance:", np.var(arr))    # Output: 200.0
    print("Min:", np.min(arr))         # Output: 10
    print("Max:", np.max(arr))         # Output: 50
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Percentiles & Quantiles**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

    print("25th Percentile:", np.percentile(arr, 25))  # Output: 3.25
    print("50th Percentile (Median):", np.percentile(arr, 50))  # Output: 5.5
    print("75th Percentile:", np.percentile(arr, 75))  # Output: 7.75
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Correlation & Covariance**

    ``` python
    python
    CopyEdit
    x = np.array([10, 20, 30, 40, 50])
    y = np.array([5, 10, 15, 20, 25])

    # Correlation Coefficient
    print("Correlation:\n", np.corrcoef(x, y))

    # Covariance
    print("Covariance:\n", np.cov(x, y))
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Mode (Using SciPy)**

    NumPy **doesn’t** have a built-in mode function, but we can use
    SciPy.

    ``` python
    python
    CopyEdit
    from scipy import stats

    arr = np.array([1, 2, 2, 3, 3, 3, 4, 4])

    mode = stats.mode(arr)
    print("Mode:", mode.mode[0])  # Output: 3
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. Histogram Binning**

    ``` python
    python
    CopyEdit
    data = np.random.randint(0, 100, size=20)

    hist, bins = np.histogram(data, bins=5)
    print("Bins:", bins)
    print("Frequency:", hist)
    ```

    ------------------------------------------------------------------------

-   **Random Number Generation**

    \## **✅ 1. Generate Random Integers**

    ``` python
    python
    CopyEdit
    import numpy as np

    print(np.random.randint(1, 10))  # Single random integer (1 to 9)
    print(np.random.randint(1, 10, size=5))  # Array of 5 random integers
    print(np.random.randint(1, 10, size=(3, 3)))  # 3x3 matrix of random integers
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Generate Random Floats (Uniform Distribution)**

    ``` python
    python
    CopyEdit
    print(np.random.rand())  # Single random float (0 to 1)
    print(np.random.rand(3, 3))  # 3x3 matrix of random floats
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Normal (Gaussian) Distribution**

    ``` python
    python
    CopyEdit
    print(np.random.randn())  # Single random number from normal distribution
    print(np.random.randn(3, 3))  # 3x3 matrix from normal distribution
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. Set a Random Seed (Reproducibility)**

    ``` python
    python
    CopyEdit
    np.random.seed(42)  # Set seed for reproducibility
    print(np.random.randint(1, 10, size=5))  # Same result every time
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. Generate Random Samples from a List (`choice()`)**

    ``` python
    python
    CopyEdit
    arr = ['apple', 'banana', 'cherry']
    print(np.random.choice(arr))  # Randomly pick one element
    print(np.random.choice(arr, size=5, replace=True))  # Random sample with replacement
    ```

    ------------------------------------------------------------------------

    \## **✅ 6. Shuffle an Array (`shuffle()`)**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])
    np.random.shuffle(arr)
    print(arr)  # Shuffled array
    ```

    ------------------------------------------------------------------------

    \## **✅ 7. Permutation of Elements (`permutation()`)**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])
    print(np.random.permutation(arr))  # Returns a shuffled copy (original remains unchanged)
    ```

    ------------------------------------------------------------------------

-   **Broadcasting & Vectorization**

    \## **✅ 1. What is Vectorization?**

    🚀 **Vectorization** means applying operations to entire arrays
    **without explicit loops**, making computations much faster!

    \### **🔴 Slow Python Loop**

    ``` python
    python
    CopyEdit
    import numpy as np

    arr = np.array([1, 2, 3, 4, 5])
    result = []
    for x in arr:
        result.append(x * 2)
    print(result)  # Output: [2, 4, 6, 8, 10]
    ```

    \### **🟢 Fast NumPy Vectorized Operation**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])
    result = arr * 2  # Vectorized operation
    print(result)  # Output: [2 4 6 8 10]
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. What is Broadcasting?**

    🚀 **Broadcasting** allows NumPy to perform operations on arrays of
    **different shapes** without extra memory.

    \### **🔹 Example 1: Scalar Broadcasting**

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])
    print(arr + 10)
    # Output: [11 12 13 14 15]  (10 is added to each element)
    ```

    ------------------------------------------------------------------------

    \### **🔹 Example 2: Array Broadcasting (Different Shapes)**

    ``` python
    python
    CopyEdit
    A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
    B = np.array([1, 2, 3])  # Shape (1,3)

    print(A + B)
    # Output:
    # [[2 4 6]
    #  [5 7 9]]
    ```

    ------------------------------------------------------------------------

    \### **🔹 Example 3: Incompatible Shapes (Error)**

    ``` python
    python
    CopyEdit
    A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
    B = np.array([1, 2])  # Shape (1,2)

    print(A + B)  # ❌ ERROR! Shapes are not compatible.
    ```

    ------------------------------------------------------------------------

-   **Boolean & Logical Operations**

    \## **✅ 1. Boolean Arrays (True/False Values)**

    ``` python
    python
    CopyEdit
    import numpy as np

    arr = np.array([1, 2, 3, 4, 5])
    bool_arr = arr > 2  # Condition check
    print(bool_arr)
    # Output: [False False  True  True  True]
    ```

    ------------------------------------------------------------------------

    \## **✅ 2. Filtering Using Boolean Masking**

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50])
    filtered = arr[arr > 25]  # Keep values greater than 25
    print(filtered)
    # Output: [30 40 50]
    ```

    ------------------------------------------------------------------------

    \## **✅ 3. Logical Operations (`&`, `|`, `~`)**

    | **Operator** | **Description** | **Example**             |
    |--------------|-----------------|-------------------------|
    | `&`          | Logical AND     | `(arr > 2) & (arr < 5)` |
    | `|`          | Logical OR      |                         |
    | `~`          | Logical NOT     | `~(arr > 3)`            |

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])

    print(arr[(arr > 2) & (arr < 5)])  # AND condition
    # Output: [3 4]

    print(arr[(arr == 1) | (arr == 3)])  # OR condition
    # Output: [1 3]

    print(arr[~(arr > 3)])  # NOT condition (inverts True/False)
    # Output: [1 2 3]
    ```

    ------------------------------------------------------------------------

    \## **✅ 4. `np.where()` for Conditional Selection**

    ``` python
    python
    CopyEdit
    arr = np.array([10, 20, 30, 40, 50])
    new_arr = np.where(arr > 25, "High", "Low")
    print(new_arr)
    # Output: ['Low' 'Low' 'High' 'High' 'High']
    ```

    ------------------------------------------------------------------------

    \## **✅ 5. `np.any()` and `np.all()`**

    | **Function** | **Description**                                       | **Example**       |
    |------------------------|------------------------|------------------------|
    | `np.any()`   | Returns `True` if **any** condition is met            | `np.any(arr > 4)` |
    | `np.all()`   | Returns `True` if **all** elements meet the condition | `np.all(arr > 0)` |

    ``` python
    python
    CopyEdit
    arr = np.array([1, 2, 3, 4, 5])

    print(np.any(arr > 4))  # True (at least one element > 4)
    print(np.all(arr > 0))  # True (all elements > 0)
    ```

    ------------------------------------------------------------------------